# -*- coding: utf-8 -*-
"""Netflix Data Exploration Business Case1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A5Z6O0I1p3Y0VFleKI5Ajw745Ur-iKc4

# **Netflix Data Exploration Business Case**
- Name - Sanjesh Chourasia
- Submission date - 28/09/2024

## **1. Project Overview**

Netflix, a global leader in video streaming, offers over 8,000 movies and TV shows to more than 200 million subscribers worldwide. This project aims to analyze data from 8,807 Netflix titles to uncover insights that can guide decisions about content production, release timing, and business growth strategies. Through this analysis, we will answer key questions about popular content types, release patterns, and country-specific production trends.









## **Dataset**

[Netflix Dataset]( https://www.kaggle.com/shivamb/netflix-shows)

The dataset consists of movies and TV shows available on Netflix. Each entry includes details such as:

* Show ID: Unique ID of the show
* Type: Movie or TV show
* Title: Title of the show
* Director: Director of the show
* Cast: Actors involved
* Country: Country of production
* Date Added: When it was added to Netflix
* Release Year: Year of release
* Rating: TV rating (e.g., PG, TV-MA)
* Duration: Number of seasons or runtime in minutes
* Listed In: Genre
* Description: A brief summary of the show

This dataset provides a broad range of information to analyze, from content type and release dates to cast and country-specific trends.

## **2. Importing the libraries and the dataset**

In this project, I am using **NumPy** for working with arrays, **Pandas** for handling and analyzing data with DataFrames, and both **Matplotlib and Seaborn** for creating visualizations and charts."
"""

# Importing libraries.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# reading csv file from google drive.
from google.colab import drive
drive.mount('/content/drive')

# Loading data.
df = pd.read_csv('/content/drive/My Drive/python data analyst project scaler/netflix.csv')
df.head(2)

df.shape

"""Dataset contain 8807 rows and 12 columns."""

df.info()

df.describe().T

# list of columns.
df.columns

# columns with datatype int.
numerical_column_name = df.select_dtypes(include=['number']).columns
print('Numerical Columns:', numerical_column_name)

# column with datatype object.
object_column_name = df.select_dtypes(include=['object']).columns
print('Object Columns:', object_column_name)

#unique value
df.nunique()

"""## **3. Data Cleaning**"""

# Creating copy fo df.
df_c1 = df.copy()

# null values (before cleaning data)
null = df_c1.isnull().sum()

# percantage null value
null_= round((null/len(df_c1))*100,2)

# concating null and null_ columns.
con = pd.concat([null,null_],axis=1,keys=['null_values','per_null'])
con

"""
In our dataset, the director, cast, and country columns contain a majority of the null values."""

# Replacing null values with 'Unknown'
df_c1['director'].fillna('Unknown_director', inplace=True)
df_c1['cast'].fillna('Unknown_cast',inplace=True)
df_c1['country'].fillna('Unknown_country', inplace=True)

# Replacing null values with 'Unknown' and changing datatype of date column.
df_c1['date_added'].fillna('Unknown_date_added', inplace=True)
df_c1['date_added'] = pd.to_datetime(df_c1['date_added'], errors='coerce')

# Replacing null values in rating column with mode value.
df_c1['rating'].fillna(df['rating'].mode(), inplace=True)

# spliting and changing datatype of duration.
df_c1[['duration', 'duration_type']] = df_c1['duration'].str.split(' ', expand=True)
df_c1['duration'].fillna(0, inplace=True)
df_c1['duration_type'].fillna('Unknown_duration_type', inplace=True)

df_c1.head(2)

"""## **4. Analysing data**

### **1. Analysing each categorical variable both using graphical and nongraphical analysis.**

***1.1 Number of sessions in each Tv shows***
"""

# filtring tv show data.
tv = df_c1[df_c1['type'] == 'TV Show']

# grouping and calculating count of duration.
tv_g = tv.groupby(['duration'])['title'].count().sort_values(ascending=False).reset_index()
tv_g.head()

sns.barplot(x='duration', y='title', data=tv_g, palette='cool', hue='duration', legend=False)
plt.xlabel('Number of Sessions')
plt.ylabel('Tv Show')
plt.title('Number of Sessions in Each Tv Show')
plt.show()

"""Most TV Shows has only one session.

***1.2 Rating.***
"""

rating = df_c1.groupby(['rating'])['title'].count().sort_values(ascending=False).reset_index().head(10)
rating

sns.barplot(y='rating', x='title', data=rating, palette='cool', hue='rating', legend=False)
plt.xlabel('Rating')
plt.ylabel('Number of Shows')
plt.title('Rating')
plt.show()

"""The majority of shows on Netflix are produced for an adult audience, with a TV-MA rating.

***1.3. Length of movies.***
"""

movies = df_c1[df_c1['type'] == 'Movie']

# converting datatype into int
movies['duration'] = movies['duration'].astype(int)

movies.describe()

plt.hist(movies['duration'], bins=20)

"""Average duration of most movies on Netflix varies from 90 min to 120 min.

### **2. Comparison of TV Shows and Movies.**
"""

type1 = df_c1['type'].value_counts('')
type1.reset_index()

"""There are total 6131 movies and 2676 TV Shows in Netflix."""

# calculating number of movies and tv shows
type1 = df_c1['type'].value_counts()
print('Distribution of Movies and Tv Shows',type1)

# plotting graph
plt.figure(figsize=(4,3))
plt.bar(type1.index, type1.values , color= ['blue','orange'], width = 0.5, align = 'center')
plt.xlabel('Types')
plt.ylabel('Count')
plt.title('Distribution of Movie vs TV shows')
plt.show()

"""Data is distributed among Movies and Tv showes. There are total 6131 Movies and 2676 TV Showes."""

plt.figure(figsize=(4,3))
plt.pie(data=type, x=type1.values, labels=type1.index, colors= ['blue','orange'], autopct='%.2f%%',explode = [0.1,0],shadow = True)
plt.title('Distribution of Movie vs TV shows')
plt.show()

"""Distrubution of Movies is 69.62% and TV Shows is 30.38%.

***2.1. Finding the number of movies produced in each country and pick the top 10***
***countries.***
"""

# selecting movies data only.
movies = df_c1[(df_c1['type'] == 'Movie') & (df_c1['country'] != 'Unknown_country')]
movies.head(2)

# unnesting country columns
movies['country1'] = movies['country'].str.split(', ')
movies['country1']

# Explode the genres into individual rows
movies= movies.explode('country1')

# group by each country and counting unique numbers of movies.
c = movies.groupby(['country1'])['release_year'].count().sort_values(ascending=False).head(10)
c.reset_index()

# ploting bar graph.
plt.figure(figsize=(5,3))
plt.barh(c.index,c.values, color=['b'])
plt.xlabel('Number of Movies')
plt.ylabel('Country')
plt.title('Number of Movies Produced Across Different Countries')
plt.show()

"""The United States produces the highest number of movies (2,751), followed by India with 962 and the United Kingdom with 532.

***2.2. Finding the number of Tv-Shows produced in each country and pick the top 10***
"""

tv = df_c1[(df_c1['type'] == 'TV Show') & (df_c1['country'] != 'Unknown_country')]
tv.head(2)

tv['country1'] = tv['country'].str.split(', ')
tv['country1']
# Explode the genres into individual rows
tv= tv.explode('country1')

b = tv.groupby(['country1'])['release_year'].count().sort_values(ascending=False).head(10)
print(b.reset_index())

plt.figure(figsize = (5,3))
plt.barh(b.index,b.values,color='orange')
plt.xlabel('Country')
plt.ylabel('Number of Tv Shows')
plt.title('Tv Shows Produced Across Different Countries')
plt.show()

"""The United States produces the highest number of TV shows (938), followed by the United Kingdom with 272 shows and Japan with 199 shows.

### **3. What is the best time to launch a TV show?**
"""

#creating copy of df_c1 dataset.
date = df_c1.copy()
date.head(2)

# chacking data type of date_added column.
date.info()

date['date_added'].isnull().sum()

# droping null values from date_added column
date.dropna(subset=['date_added'], inplace=True)

date['date_added'].isnull().sum()

# creating day_added, month_added, year_added, and week_added column.
date['day_added'] = date['date_added'].dt.day
date['month_added'] = date['date_added'].dt.month
date['year_added']= date['date_added'].dt.year
date['week_added'] = date['date_added'].dt.isocalendar().week

# Create a week-of-month function
def week_of_month(date):
    first_day = date.replace(day=1)
    return (date.day + first_day.weekday()) // 7 + 1

# Apply the function to the date_added column
date['week_of_month'] = date['date_added'].apply(week_of_month)

"""***3.1. Finding which is the best week and month to release the Tv-show.***


   



"""

# Filtering data based on tv show
date_tv = date[date['type'] == 'TV Show']
date_tv.head(2)

# chacking rows and columns.
date_tv.shape

count_week =  date_tv.groupby(['year_added','month_added','week_added','week_of_month'])['show_id'].count().sort_values(ascending=False).reset_index()
count_week.head()

plt.figure(figsize=(6,3))
sns.barplot(x='week_of_month', y='show_id', data=count_week, color = 'orange',errorbar=None)
#plt.bar(x = count_week['week_added'], height = count_week['show_id'],color='red') # Changed y to height
plt.xlabel('Weeks_in_Month')
plt.ylabel('Number of Tv Shows')
plt.title('Tv Shows Produced Across Different Week in Month')
plt.show()

"""The highest number of tv shows are released in the first week of the month, making it the best time to release tv shows."""

# Convert the index to columns
print(count_week)
plt.figure(figsize=(6,3))
sns.barplot(x='month_added', y='show_id', data=count_week, color = 'orange',errorbar=None)
#plt.bar(x = count_week['week_added'], height = count_week['show_id'],color='red') # Changed y to height
plt.xlabel('Month')
plt.ylabel('Number of Tv Shows')
plt.title('Tv Shows Produced Across Different Month')
plt.show()

"""The highest number of tv show relised in October."""

plt.figure(figsize=(6,3))
sns.barplot(x='year_added', y='show_id', data=count_week, color = 'orange',errorbar=None)
#plt.bar(x = count_week['week_added'], height = count_week['show_id'],color='red') # Changed y to height
plt.xlabel('Year')
plt.ylabel('Number of Tv Shows')
plt.title('Tv Shows Produced Across Different Year')
plt.show()

"""Highest number of tv shows relised in year 2021.

***3.2. Finding which is the best week and month to release the Movies***
"""

date_movie = date[date['type'] == 'Movie']
date_movie.head(2)

date_movie.shape

count_movies = date_movie.groupby(['year_added','month_added','week_added','week_of_month'])['show_id'].count().sort_values(ascending=False).reset_index()
count_movies.head()

plt.figure(figsize=(6,3))
sns.barplot(x='week_of_month', y='show_id', data=count_movies, color = 'blue',errorbar=None)
plt.xlabel('Week_of_month')
plt.ylabel('Number of Movies')
plt.title('Movies Produced Across Different Weeks in Month')
plt.show()

"""
The highest number of movies are released in the first week of the month, making it the best time to release a movie."""

plt.figure(figsize = (6,3))
sns.barplot(x='month_added',y='show_id',data=count_movies,color='blue',errorbar=None)
plt.xlabel('Month')
plt.ylabel('Number of Movies')
plt.title('Movies Produced Acress Different Month')
plt.show()

"""The highest number of movies are released in January, April, and July."""

plt.figure(figsize=(6,3))
sns.barplot(x='year_added',y='show_id',data=count_movies,color='blue',errorbar=None)
plt.xlabel('Year')
plt.ylabel('Number of Month')
plt.title('Movies Produced Across Different Year')
plt.show()

"""Higest number of movie rekised in 2021 followed by 2019.

### **4. Analysis of actors/directors of different types of shows/movies.**

***4.1. Identify the top 10 actors who have appeared in most movies or TV shows.***
"""

actor = date.copy()
actor = actor[actor['cast'] != 'Unknown_cast']

actor['actor1'] = actor['cast'].str.split(',')
actor = actor.explode('actor1')
actor.head(2)

actor_count = actor.groupby(['actor1'])['title'].count().sort_values(ascending=False).reset_index().head(10)
actor_count

plt.figure(figsize=(6,3))
sns.barplot(x='title', y='actor1', data=actor_count, palette='cool', hue='actor1', legend=False)
plt.xlabel('Number of Movies/Tv Shows')
plt.ylabel('Actor')
plt.title('Top 10 Actors')
plt.show()

"""Anupam Kher	is top actor who apper in 39 shows followed by Rupa Bhimani	(31 show) and Takahiro Sakurai (29 show).

***4.2. Identify the top 10 directors who have appeared in most movies or TV shows.***
"""

director = date.copy()
director = director[director['director'] != 'Unknown_director']

director['director1'] = director['director'].str.split(',')
director = director.explode('director1')
director.head(2)

director_count = director.groupby(['director1'])['title'].count().sort_values(ascending=False).reset_index().head(10)
director_count

plt.figure(figsize=(6,3))
sns.barplot(x='title', y='director1', data=director_count, palette='cool', hue='director1', legend=False)
plt.xlabel('Number of Movies/Tv Shows')
plt.ylabel('Director')
plt.title('Top 10 Director')
plt.show()

"""Rajiv Chilaka	is top director followed by Jan Suter and Raúl Campos.

### **5. Which genre  movies/tv shows are more popular or produced more**
"""

# creating copy of data as genre
genre = date.copy()
genre['genre1'] = genre['listed_in'].str.split(',')
genre = genre.explode('genre1')
genre.head(2)

genre_count = genre.groupby(['genre1'])['title'].count().sort_values(ascending=False).reset_index().head(10)
genre_count

plt.figure(figsize=(6,3))
sns.barplot(x='title',y='genre1', data=genre_count, palette='cool', hue='genre1', legend=False)
plt.xlabel('Number of Movies')
plt.ylabel('Genre')
plt.title('Most popular genre')
plt.show()

"""Most popular genra is International Movies followed by Dramas and Comedies."""

from wordcloud import WordCloud

plt.subplots(figsize=(6,`))
wordcloud=WordCloud(
background_color="white",
    width=1920,
    height=1080).generate(" ".join(genre['genre1']))
plt.imshow(wordcloud)
plt.axis("off")
plt.savefig("country.png")
plt.show()

"""### **6. Insights:**

1. **Number of Seasons in TV Shows:**
   - Most TV shows on Netflix have only one season.

2. **TV Show Ratings:**
   - The majority of Netflix shows are rated TV-MA, indicating they are primarily produced for an adult audience.

3. **Movie Duration:**
   - The average length of most Netflix movies ranges between 90 to 120 minutes.

4. **Comparison of TV Shows and Movies:**
   - Netflix has a total of 6,131 movies and 2,676 TV shows.
   - The distribution is 69.62% movies and 30.38% TV shows.

5. **Top 10 Countries Producing Movies:**
   - The United States leads with 2,751 movies, followed by India with 962 and the United Kingdom with 532.

6. **Top 10 Countries Producing TV Shows:**
   - The United States produces the most TV shows (938), followed by the United Kingdom (272) and Japan (199).

7. **Best Time to Release TV Shows and Movies:**

   - **TV Show Analysis:**
     - **Best Week:** Most TV shows are released in the first week of the month, making it the best time to launch new shows.
     - **Best Month:** October sees the highest number of TV show releases.
     - **Best Year:** 2021 had the highest number of TV show releases, showing an increasing trend in production over the years.

   - **Movie Analysis:**
     - **Best Week:** The first week of the month is also the best time to release movies.
     - **Best Months:** January, April, and July are the months with the most movie releases.
     - **Best Year:** 2021 had the most movie releases, followed by 2019, indicating consistent growth in movie production over time.

8. **Top 10 Actors Appearing in Movies or TV Shows:**
   - Anupam Kher appears in the most shows (39), followed by Rupa Bhimani (31) and Takahiro Sakurai (29).

9. **Top 10 Directors with the Most Movies or TV Shows:**
   - Rajiv Chilaka is the top director, followed by Jan Suter and Raúl Campos.

10. **Most Popular Genres:**
    - The most popular genre on Netflix is International Movies, followed by Dramas and Comedies.



### **7. Recommendations for Netflix to Grow Business in Different Countries:**

1. **Expand Production in Growing Markets:**
   - Since India and the United Kingdom are among the top producers of both movies and TV shows, Netflix should continue to invest in local content and expand partnerships with filmmakers in these regions.

2. **Focus on Popular Genres:**
   - International Movies, Dramas, and Comedies are the most popular genres. Producing more content in these genres will likely attract a broader audience.

3. **Target Adult Audience:**
   - With the majority of TV shows rated for adult audiences, Netflix should focus on producing more adult-themed content, such as dramas and thrillers, while also considering expanding family-friendly content to reach more viewers.

4. **Optimize Release Times:**
   - Since the first week of the month and certain months (January, April, July, and October) show the highest number of releases, Netflix can strategically plan new releases during these periods to maximize viewership.

5. **Promote Top Actors and Directors:**
   - Netflix should consider highlighting shows and movies featuring top actors like Anupam Kher and directors like Rajiv Chilaka in global promotions, especially in regions where these talents are well known.

6. **Increase Production in Emerging Markets:**
   - While the United States dominates content production, there is potential for growth in emerging markets like Japan, where Netflix can increase its production of local shows and movies.

By focusing on these strategies, Netflix can continue to grow its presence globally and attract more subscribers across different markets.

### **7. Recommendations for Netflix to Grow Business in Different Countries:**

1. **Expand Production in Growing Markets:**
   - Since India and the United Kingdom are among the top producers of both movies and TV shows, Netflix should continue to invest in local content and expand partnerships with filmmakers in these regions.

2. **Focus on Popular Genres:**
   - International Movies, Dramas, and Comedies are the most popular genres. Producing more content in these genres will likely attract a broader audience.

3. **Target Adult Audience:**
   - With the majority of TV shows rated for adult audiences, Netflix should focus on producing more adult-themed content, such as dramas and thrillers, while also considering expanding family-friendly content to reach more viewers.

4. **Optimize Release Times:**
   - Since the first week of the month and certain months (January, April, July, and October) show the highest number of releases, Netflix can strategically plan new releases during these periods to maximize viewership.

5. **Promote Top Actors and Directors:**
   - Netflix should consider highlighting shows and movies featuring top actors like Anupam Kher and directors like Rajiv Chilaka in global promotions, especially in regions where these talents are well known.

6. **Increase Production in Emerging Markets:**
   - While the United States dominates content production, there is potential for growth in emerging markets like Japan, where Netflix can increase its production of local shows and movies.

By focusing on these strategies, Netflix can continue to grow its presence globally and attract more subscribers across different markets.
"""





